wellcomecollection/docs

rfcs/018-pipeline_tracing/README.md

Rendered markdown: https://github.com/wellcomecollection/docs/blob/pipeline-tracing/rfcs/018-pipeline_tracing/README.md

RFC: Add pipeline tracing

---

incident_retros/2020-01-15_app-index-sync.md

Writing up the retro for the model / index shape sync.
__TODO:__

add draft of retro for model / index sync

---

incident_retros/2020-01-15_app-index-sync.md

add RFC to retro

---

people/feeback.md

Adds how we collect feedback on what we're working on and how we're doing it.
Forms part of PDRs / Promotions / etc.

add people/feedback

---

rfcs/016-holdings_service/README.md
rfcs/020-locations_requesting/README.md

Note that making a request can now fail with a 409 conflict!

Update stacks doc with latest request implementation

---

rfcs/021-data_science_in_the_pipeline/README.md

https://github.com/wellcomecollection/docs/blob/data-science-pipeline/rfcs/021-data_science_in_the_pipeline/README.md

RFC: Data science in the pipeline

---

rfcs/022-logging/example/.gitignore
rfcs/022-logging/example/README.md
rfcs/022-logging/example/check_deployment.sh
rfcs/022-logging/example/fluentbit/Dockerfile
rfcs/022-logging/example/fluentbit/build.sh
rfcs/022-logging/example/fluentbit/extra.conf
rfcs/022-logging/example/iam.tf
rfcs/022-logging/example/locals.tf
rfcs/022-logging/example/main.tf
rfcs/022-logging/example/output.tf
rfcs/022-logging/example/provider.tf
rfcs/022-logging/example/redeploy.sh
rfcs/022-logging/example/terraform.tf

Adds a TF stack example to bring up a working logging soltution.

Adds logging example

---

rfcs/023-images-endpoint/README.md

https://github.com/wellcomecollection/docs/blob/images-endpoint/rfcs/023-images-endpoint/README.md

RFC: Images endpoint

---

rfcs/002-archival_storage/README.md

For https://github.com/wellcomecollection/platform/issues/4551

Update the storage provider names in the storage service RFC

---

rfcs/021-data_science_in_the_pipeline/README.md

Kind of a work in progress, but I think I'll be trying these changes out first.
https://github.com/wellcomecollection/docs/blob/data-science-rfc-updates/rfcs/021-data_science_in_the_pipeline/README.md

Data science in the pipeline architecture updates

---

rfcs/030-pipeline_merging/README.md

Rendered version https://github.com/wellcomecollection/docs/tree/pipeline_merging/rfcs/030-pipeline_merging

Add pipeline merging RFC

---

INCIDENTS.md

Describing our process for dealing with incidents on the Wellcome Collection digital platform.

Incident response protocol

---

rfcs/032-calm-deletions/README.md

Still a bit of a wip, thought I'd get it out for discussion before refining further.
Formatted RFC: https://github.com/wellcomecollection/docs/blob/calm-deletions-rfc/rfcs/032-calm-deletions/README.md

RFC: Calm deletion watcher

---

rfcs/034-location_location_location/README.md
rfcs/034-location_location_location/closed_locations.csv
rfcs/034-location_location_location/not_closed_locations.csv

This is part of https://github.com/wellcomecollection/platform/issues/4996
Rendered version: https://github.com/wellcomecollection/docs/blob/location-location-location/rfcs/034-location_location_location/README.md

Describe the requirements for our Location model

---

rfcs/037-api-faceting-principles/README.md

This is intended to be a data-agnostic specification of how we expect our API to work, particularly regarding filtering and aggregations. Formatted file here: https://github.com/wellcomecollection/docs/blob/api-expectations/rfcs/037-api-faceting-principles/README.md

Add RFC for API principles/expectations

---

rfcs/041-miro-data-changes/README.md

For https://github.com/wellcomecollection/platform/issues/5176
Rendered version: https://github.com/wellcomecollection/docs/blob/tracking-changes-to-miro-data/rfcs/041-miro-data-changes/README.md

Add a brief RFC for tracking changes to Miro data

---

GLOSSARY.md

Rendered: https://github.com/wellcomecollection/docs/blob/glossary/GLOSSARY.md

Add a glossary

---

rfcs/044-patron-deletions/README.md

Rendered version: https://github.com/wellcomecollection/docs/blob/f143168ccbc0a4285d5090d777c89d1b51c67eb7/rfcs/044-patron-deletions/README.md

RFC 044: Patron Deletions

---

rfcs/047-catalogue-api-index-structure.md

Closes https://github.com/wellcomecollection/platform/issues/5487; fleshing out https://github.com/wellcomecollection/platform/issues/5449

RFC 047: Changing the structure of the Catalogue API index

---

rfcs/046-transitive-sierra-hierarchies/README.md
rfcs/046-transitive-sierra-hierarchies/queries.txt

This relates to https://github.com/wellcomecollection/platform/issues/5479
rendered: https://github.com/wellcomecollection/docs/blob/1e3fd3183e536fe27a6aee99317dba5170c93dec/rfcs/046-transitive-sierra-hierarchies/README.md

046 transitive Sierra hierarchies

---

rfcs/048-concepts-rfcs/README.md

Rendered version: https://github.com/wellcomecollection/docs/blob/rfc-concepts-work/rfcs/048-concepts-rfcs/README.md

RFC 048: Concepts work plan

---

rfcs/050-concepts-api/README.md
rfcs/README.md

For https://github.com/wellcomecollection/platform/issues/5536
Rendered version: https://github.com/wellcomecollection/docs/blob/050-concepts-api/rfcs/050-concepts-api/README.md
This follows the discussion at planning this morning. I've tried to capture everything we said so we can continue that discussion here. The sense I got from this morning is that we have consensus about a set of "core" fields (id, label, identifiers), and then we need to think more about everything else.

RFC 050: initial ideas for the design of the concepts API

---

rfcs/053-lambda-logging/README.md

Rendered version: https://github.com/wellcomecollection/docs/blob/lambda-logging-rfc/rfcs/053-lambda-logging/README.md

Lambda logging RFC

---

rfcs/054-prismic-api/README.md
rfcs/055-prismic-api/README.md
rfcs/055-prismic-api/articles.md
rfcs/055-prismic-api/events.md
rfcs/055-prismic-api/exhibitions.md
rfcs/055-prismic-api/future-versions.md

[Rendered version of the RFC](https://github.com/wellcomecollection/docs/blob/prismic-api-rfc/rfcs/055-prismic-api/README.md) 
This PR closes https://github.com/wellcomecollection/platform/issues/5661

Content API RFC

---

GLOSSARY.md

In an effort to ensure everyone uses the same language and help with onboarding, here is a incomplete glossary of the terms used in relation to the website content and context. Please contribute to them as I don't hold all the necessary knowledge (yet)!
A term might also be used differently on the UI, in Prismic and on the Backend, so we could make that distinction.

Add internal terms to glossary

---

rfcs/059-splitting-pipeline-terraform/README.md
rfcs/README.md

For https://github.com/wellcomecollection/catalogue-pipeline/issues/2393

Add an RFC for splitting the pipeline Terraform

---

GLOSSARY.md

Adds Audience, Interpretation types and Place as well as adds to Location.
People understand the definitions
It confuses people further 😄

Add terms to glossary

---

GLOSSARY.md

Add a glossary entry for EBSCO.

Add EBSCO to the glossary.

---

adr/github_security.md

This change adds an ADR related to providing visibility of and removing potential security issues in our services.
Shared understanding of necessary security improvements, allowing more effective work towards a common goal.

GitHub Security ADR

---

adr/github_groups_permissions.md

Tweak wording of github group ADR

ADR: Update GitHub teams docs to reflect reality.

---

rfcs/065-library-data-link-explorer/README.md

Adds RFC 065 - detailing the Library Data Link Explorer roadmap and process
All comments and pointers appreciated. 
For https://github.com/wellcomecollection/platform/issues/5833

065-rfc-library-data-link-explorer

---

rfcs/070-python_builds/README.md
rfcs/070-python_builds/appendix.md

A plan for addressing inconsistencies in Python build systems: https://github.com/wellcomecollection/platform/issues/5955
Read it, does it make sense?  Implement the recommendations, does it simplify things?
Once implemented, it will be easier to manage Python projects across all our repositories.
The point of writing this is to mitigate the risk of adding yet another build tool and/or process.

Python build and deploy

---

rfcs/075-updated_adapters/README.md
rfcs/075-updated_adapters/load_adapter_data.py
rfcs/075-updated_adapters/upsert_dummy_data.py
rfcs/README.md

For https://github.com/wellcomecollection/platform/issues/6016
The RFC is understandable and agreed by Platform developers.

RFC 075: Using Apache Iceberg tables in Catalogue Pipeline adapters
